config/routes.rb
Rails.application.routes.draw do
  resources :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/property.rb
class Property < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  def index
    @pagy, @properties = pagy(Property.order(id: :asc), items: 5)
  end

  def show
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)

    if @property.save
      respond_to do |format|
        format.html { redirect_to properties_path, notice: "Property was successfully created." }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @property.update(property_params)
      respond_to do |format|
        format.html { redirect_to properties_path, notice: "Property was successfully updated." }
        format.turbo_stream
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_path,
                                notice: "Property was successfully destroyed." }
      format.turbo_stream
    end
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboRailsIntro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/properties/_form.html.erb
<%= simple_form_for property, html: { class: "property form" } do |f| %>
  <% if property.errors.any? %>
    <div class="error-message">
      <%= property.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/properties/_property.html.erb
<%= turbo_frame_tag property do %>
  <div class="property">
    <%= link_to property.name, property_path(property), data: {turbo_frame: '_top'} %>
    <div class="property__actions">
      <%= button_to "Delete",
                    property_path(property),
                    method: :delete,
                    class: "btn btn--light" %>
      <%= link_to "Edit",
                  edit_property_path(property),
                  class: "btn btn--light" %>
    </div>
  </div>
<% end %>

app/views/properties/create.turbo_stream.erb
<%= turbo_stream.prepend "properties", partial: "properties/property", locals: { property: @property } %>
<%= turbo_stream.update Property.new, "" %>

app/views/properties/destroy.turbo_stream.erb
<%= turbo_stream.remove @property %>

app/views/properties/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to property"), property_path(@property) %>

  <div class="header">
    <h1>Edit property</h1>
  </div>
  <%= turbo_frame_tag @property do %>
    <%= render "form", property: @property %>
  <% end %>
</main>

app/views/properties/index.html.erb
<main class="container">
  <%= turbo_frame_tag 'first_turbo_frame' do %>
    <div class="header">
      <h1>Properties</h1>
      <%= link_to "New property",
                  new_property_path,
                  data: { turbo_frame: dom_id(Property.new) },
                  class: "btn btn--primary" %>
    </div>
  <% end %>
<%= turbo_frame_tag Property.new %>
  <%= turbo_frame_tag 'properties' do %>
    <%= turbo_frame_tag "page_#{@pagy.page}" do %>
      <%= render @properties %>
      <% if @pagy.next %>
        <%= turbo_frame_tag "page_#{@pagy.next}",
                            loading: :lazy,
                            src: pagy_url_for(@pagy, @pagy.next) %>
      <% else %>
        No more properties
      <% end %>
    <% end %>
  <% end %>
</main>

app/views/properties/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to properties"), properties_path %>

  <div class="header">
    <h1>New property</h1>
  </div>
  <%= turbo_frame_tag @property do %>
    <%= render "form", property: @property %>
  <% end %>
</main>

app/views/properties/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to properties"), properties_path %>
  <div class="header">
    <h1>
      <%= @property.name %>
    </h1>
  </div>
</main>

app/views/properties/update.turbo_stream.erb
<%# app/views/properties/update.turbo_stream.erb %>

<%= turbo_stream.update @property, @property %>